version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: username # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: default_database
    ports:
      - 5444:5444
    volumes:
      - dbdata:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  dbdata:
