version: "3"

services:
  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    restart: always
    environment:
      PGRST_DB_URI: postgres://username:password@db:5432/default_database
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_OPENAPI_MODE: follow-privileges
      PGRST_JWT_SECRET: 41623342585636885225690176263249
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: username # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: default_database
    ports:
      - 3211:5432
    volumes:
      - dbdata:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/

volumes:
  dbdata:
