import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import axios from "axios";

const Home: NextPage = () => {
  async function testDbConn() {
    console.log("ok");
    const result = await axios.get("api/signup");
    console.log(result);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={testDbConn}> Test DB Connection</button>
    </div>
  );
};

export default Home;
